---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.9-alpine3.14
  amd64: ghcr.io/home-assistant/amd64-base-python:3.9-alpine3.14
  armhf: ghcr.io/home-assistant/armhf-base-python:3.9-alpine3.14
  armv7: ghcr.io/home-assistant/armv7-base-python:3.9-alpine3.14
  i386: ghcr.io/home-assistant/i386-base-python:3.9-alpine3.14
labels:
  org.opencontainers.image.title: "Let's Encrypt ECDSA"
  org.opencontainers.image.description: "SSL Certificate from Let's Encrypt with ECDSA"
  org.opencontainers.image.source: "https://github.com/WillCodeForCats/ha-addon-letsencrypt-ecdsa"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  CRYPTOGRAPHY_VERSION: 36.0.2
  CERTBOT_DNS_AZURE_VERSION: 1.5.0
  CERTBOT_DNS_DIRECTADMIN_VERSION: 0.0.24
  CERTBOT_DNS_HETZNER_VERSION: 1.0.5
  CERTBOT_DNS_GOOGLE_DOMAINS_VERSION: 0.1.11
  CERTBOT_DNS_TRANSIP_VERSION: 0.4.3
  CERTBOT_GANDI_VERSION: 1.3.2
  CERTBOT_NETCUP_VERSION: 1.1.1
  CERTBOT_NJALLA_VERSION: 1.0.0
  CERTBOT_VERSION: 1.32.0
  CERTBOT_DNS_INWX_VERSION: 2.2.0
  ACME_VERSION: 1.32.0
